spring:
  application:
    name: timesheet
  datasource:
    url: jdbc:h2:mem:timesheet
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true

    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        event:
          merge:
            entity_copy_observer: allow